name: Build and push docker image to ECR repo
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
  OIDC_ROLE: ${{ vars.OIDC_ROLE }}
  API_ECR_REPO: ${{ vars.API_ECR_REPO }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd app 
          docker build -t $ECR_REGISTRY/${{ env.API_ECR_REPO }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ env.API_ECR_REPO }}:$IMAGE_TAG
